-- ============================================================================
-- AURAWAVE DATABASE SCHEMA
-- Script de criação completo do banco de dados Oracle
-- Data: 29/10/2025
-- ============================================================================

-- ============================================================================
-- DROP TABLES (caso já existam - ordem reversa para respeitar FKs)
-- ============================================================================
DROP TABLE EVENT CASCADE CONSTRAINTS;
DROP TABLE SESSION_COLLABORATOR CASCADE CONSTRAINTS;
DROP TABLE SESSION CASCADE CONSTRAINTS;
DROP TABLE ITEM_BATCH CASCADE CONSTRAINTS;
DROP TABLE ITEM_MODEL CASCADE CONSTRAINTS;
DROP TABLE ITEM CASCADE CONSTRAINTS;
DROP TABLE BATCH_SUPPLIER CASCADE CONSTRAINTS;
DROP TABLE BATCH CASCADE CONSTRAINTS;
DROP TABLE SUPPLIER CASCADE CONSTRAINTS;
DROP TABLE MODEL_MANUFACTURER CASCADE CONSTRAINTS;
DROP TABLE MODEL_PRODUCT CASCADE CONSTRAINTS;
DROP TABLE MODEL CASCADE CONSTRAINTS;
DROP TABLE MANUFACTURER CASCADE CONSTRAINTS;
DROP TABLE PRODUCT CASCADE CONSTRAINTS;
DROP TABLE WAREHOUSE_LABORATORY CASCADE CONSTRAINTS;
DROP TABLE WAREHOUSE CASCADE CONSTRAINTS;
DROP TABLE LABORATORY CASCADE CONSTRAINTS;
DROP TABLE COLLABORATOR CASCADE CONSTRAINTS;

-- ============================================================================
-- SEQUENCES (para auto incremento dos IDs)
-- ============================================================================
DROP SEQUENCE SEQ_SUPPLIER;
DROP SEQUENCE SEQ_BATCH;
DROP SEQUENCE SEQ_MANUFACTURER;
DROP SEQUENCE SEQ_MODEL;
DROP SEQUENCE SEQ_LABORATORY;
DROP SEQUENCE SEQ_WAREHOUSE;
DROP SEQUENCE SEQ_ITEM;
DROP SEQUENCE SEQ_COLLABORATOR;
DROP SEQUENCE SEQ_SESSION;
DROP SEQUENCE SEQ_EVENT;
DROP SEQUENCE SEQ_PRODUCT;

CREATE SEQUENCE SEQ_SUPPLIER START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_BATCH START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_MANUFACTURER START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_MODEL START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_LABORATORY START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_WAREHOUSE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ITEM START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_COLLABORATOR START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_SESSION START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_EVENT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PRODUCT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- ============================================================================
-- TABELAS PRINCIPAIS (sem dependências)
-- ============================================================================

-- Tabela: SUPPLIER (Fornecedor)
CREATE TABLE SUPPLIER (
    ID NUMBER(19) NOT NULL,
    NM_SUPPLIER VARCHAR2(100 CHAR) NOT NULL,
    CPF VARCHAR2(11 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_SUPPLIER PRIMARY KEY (ID),
    CONSTRAINT UK_SUPPLIER_CPF UNIQUE (CPF),
    CONSTRAINT CK_SUPPLIER_CPF CHECK (LENGTH(CPF) = 11)
);

-- Tabela: MANUFACTURER (Fabricante)
CREATE TABLE MANUFACTURER (
    ID NUMBER(19) NOT NULL,
    NM_MANUFACTURER VARCHAR2(100 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_MANUFACTURER PRIMARY KEY (ID)
);

-- Tabela: LABORATORY (Laboratório)
CREATE TABLE LABORATORY (
    ID NUMBER(19) NOT NULL,
    NM_LABORATORY VARCHAR2(65 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_LABORATORY PRIMARY KEY (ID)
);

-- Tabela: COLLABORATOR (Colaborador)
CREATE TABLE COLLABORATOR (
    ID NUMBER(19) NOT NULL,
    NM_COLLABORATOR VARCHAR2(300 CHAR) NOT NULL,
    COD_COMPANY VARCHAR2(350 CHAR) NOT NULL,
    CPF VARCHAR2(11 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_COLLABORATOR PRIMARY KEY (ID),
    CONSTRAINT UK_COLLABORATOR_CPF UNIQUE (CPF),
    CONSTRAINT CK_COLLABORATOR_CPF CHECK (LENGTH(CPF) = 11)
);

-- ============================================================================
-- TABELAS COM DEPENDÊNCIAS DE 1º NÍVEL
-- ============================================================================

-- Tabela: BATCH (Lote) - depende de SUPPLIER
CREATE TABLE BATCH (
    ID NUMBER(19) NOT NULL,
    NM_BATCH VARCHAR2(200 CHAR) NOT NULL,
    SUPPLIER_ID_SUPPLIER NUMBER(19) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_BATCH PRIMARY KEY (ID),
    CONSTRAINT FK_BATCH_SUPPLIER FOREIGN KEY (SUPPLIER_ID_SUPPLIER) 
        REFERENCES SUPPLIER(ID) ON DELETE CASCADE
);

-- Tabela: MODEL (Modelo) - depende de MANUFACTURER
CREATE TABLE MODEL (
    ID NUMBER(19) NOT NULL,
    NM_MODEL VARCHAR2(60 CHAR) NOT NULL,
    MANUFACTURER_ID_MANUFACTURER NUMBER(19) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_MODEL PRIMARY KEY (ID),
    CONSTRAINT FK_MODEL_MANUFACTURER FOREIGN KEY (MANUFACTURER_ID_MANUFACTURER) 
        REFERENCES MANUFACTURER(ID) ON DELETE CASCADE
);

-- Tabela: WAREHOUSE (Almoxarifado) - depende de LABORATORY
CREATE TABLE WAREHOUSE (
    ID NUMBER(19) NOT NULL,
    NM_WAREHOUSE VARCHAR2(80 CHAR) NOT NULL,
    LABORATORY_ID_LABORATORY NUMBER(19) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_WAREHOUSE PRIMARY KEY (ID),
    CONSTRAINT FK_WAREHOUSE_LABORATORY FOREIGN KEY (LABORATORY_ID_LABORATORY) 
        REFERENCES LABORATORY(ID) ON DELETE CASCADE
);

-- ============================================================================
-- TABELAS COM DEPENDÊNCIAS DE 2º NÍVEL
-- ============================================================================

-- Tabela: PRODUCT (Produto) - depende de WAREHOUSE
CREATE TABLE PRODUCT (
    ID NUMBER(19) NOT NULL,
    NAME VARCHAR2(100 CHAR) NOT NULL,
    VALIDITY_DATE TIMESTAMP,
    WAREHOUSE_ID NUMBER(19) NOT NULL,
    COST_PRICE NUMBER(10,2) NOT NULL,
    STATUS VARCHAR2(20 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_PRODUCT PRIMARY KEY (ID),
    CONSTRAINT FK_PRODUCT_WAREHOUSE FOREIGN KEY (WAREHOUSE_ID) 
        REFERENCES WAREHOUSE(ID) ON DELETE CASCADE,
    CONSTRAINT CK_PRODUCT_STATUS CHECK (STATUS IN ('ACTIVE', 'INACTIVE', 'EXPIRED')),
    CONSTRAINT CK_PRODUCT_PRICE CHECK (COST_PRICE >= 0)
);

-- Tabela: ITEM - depende de MODEL e BATCH
CREATE TABLE ITEM (
    ID NUMBER(19) NOT NULL,
    NM_ITEM VARCHAR2(100 CHAR) NOT NULL,
    STATUS VARCHAR2(60 CHAR) NOT NULL,
    MODEL_ID_MODEL NUMBER(19) NOT NULL,
    BATCH_ID_BATCH NUMBER(19) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_ITEM PRIMARY KEY (ID),
    CONSTRAINT FK_ITEM_MODEL FOREIGN KEY (MODEL_ID_MODEL) 
        REFERENCES MODEL(ID) ON DELETE CASCADE,
    CONSTRAINT FK_ITEM_BATCH FOREIGN KEY (BATCH_ID_BATCH) 
        REFERENCES BATCH(ID) ON DELETE CASCADE
);

-- Tabela: SESSION (Sessão) - depende de WAREHOUSE e COLLABORATOR
CREATE TABLE SESSION (
    ID NUMBER(19) NOT NULL,
    START TIMESTAMP NOT NULL,
    "END" TIMESTAMP NOT NULL,
    WAREHOUSE_ID_WAREHOUSE NUMBER(19) NOT NULL,
    COLLABORATOR_ID_COLLABORATOR NUMBER(19) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_SESSION PRIMARY KEY (ID),
    CONSTRAINT FK_SESSION_WAREHOUSE FOREIGN KEY (WAREHOUSE_ID_WAREHOUSE) 
        REFERENCES WAREHOUSE(ID) ON DELETE CASCADE,
    CONSTRAINT FK_SESSION_COLLABORATOR FOREIGN KEY (COLLABORATOR_ID_COLLABORATOR) 
        REFERENCES COLLABORATOR(ID) ON DELETE CASCADE,
    CONSTRAINT CK_SESSION_DATES CHECK ("END" > START)
);

-- ============================================================================
-- TABELAS COM DEPENDÊNCIAS DE 3º NÍVEL
-- ============================================================================

-- Tabela: EVENT (Evento) - depende de ITEM
CREATE TABLE EVENT (
    ID NUMBER(19) NOT NULL,
    EVENT_TYPE VARCHAR2(50 CHAR) NOT NULL,
    EVENT VARCHAR2(200 CHAR) NOT NULL,
    ITEM_ID_ITEM NUMBER(19) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_EVENT PRIMARY KEY (ID),
    CONSTRAINT FK_EVENT_ITEM FOREIGN KEY (ITEM_ID_ITEM) 
        REFERENCES ITEM(ID) ON DELETE CASCADE
);

-- ============================================================================
-- TABELAS DE RELACIONAMENTO (N:N)
-- ============================================================================

-- Relacionamento: BATCH <-> SUPPLIER
CREATE TABLE BATCH_SUPPLIER (
    BATCH_ID NUMBER(19) NOT NULL,
    SUPPLIER_ID NUMBER(19) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_BATCH_SUPPLIER PRIMARY KEY (BATCH_ID, SUPPLIER_ID),
    CONSTRAINT FK_BATCH_SUPPLIER_BATCH FOREIGN KEY (BATCH_ID) 
        REFERENCES BATCH(ID) ON DELETE CASCADE,
    CONSTRAINT FK_BATCH_SUPPLIER_SUPPLIER FOREIGN KEY (SUPPLIER_ID) 
        REFERENCES SUPPLIER(ID) ON DELETE CASCADE
);

-- Relacionamento: ITEM <-> MODEL
CREATE TABLE ITEM_MODEL (
    ITEM_ID NUMBER(19) NOT NULL,
    MODEL_ID NUMBER(19) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_ITEM_MODEL PRIMARY KEY (ITEM_ID, MODEL_ID),
    CONSTRAINT FK_ITEM_MODEL_ITEM FOREIGN KEY (ITEM_ID) 
        REFERENCES ITEM(ID) ON DELETE CASCADE,
    CONSTRAINT FK_ITEM_MODEL_MODEL FOREIGN KEY (MODEL_ID) 
        REFERENCES MODEL(ID) ON DELETE CASCADE
);

-- Relacionamento: ITEM <-> BATCH
CREATE TABLE ITEM_BATCH (
    ITEM_ID NUMBER(19) NOT NULL,
    BATCH_ID NUMBER(19) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_ITEM_BATCH PRIMARY KEY (ITEM_ID, BATCH_ID),
    CONSTRAINT FK_ITEM_BATCH_ITEM FOREIGN KEY (ITEM_ID) 
        REFERENCES ITEM(ID) ON DELETE CASCADE,
    CONSTRAINT FK_ITEM_BATCH_BATCH FOREIGN KEY (BATCH_ID) 
        REFERENCES BATCH(ID) ON DELETE CASCADE
);

-- Relacionamento: MODEL <-> MANUFACTURER
CREATE TABLE MODEL_MANUFACTURER (
    MODEL_ID NUMBER(19) NOT NULL,
    MANUFACTURER_ID NUMBER(19) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_MODEL_MANUFACTURER PRIMARY KEY (MODEL_ID, MANUFACTURER_ID),
    CONSTRAINT FK_MODEL_MANUFACTURER_MODEL FOREIGN KEY (MODEL_ID) 
        REFERENCES MODEL(ID) ON DELETE CASCADE,
    CONSTRAINT FK_MODEL_MANUFACTURER_MANUFACTURER FOREIGN KEY (MANUFACTURER_ID) 
        REFERENCES MANUFACTURER(ID) ON DELETE CASCADE
);

-- Relacionamento: MODEL <-> PRODUCT
CREATE TABLE MODEL_PRODUCT (
    MODEL_ID NUMBER(19) NOT NULL,
    PRODUCT_ID NUMBER(19) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_MODEL_PRODUCT PRIMARY KEY (MODEL_ID, PRODUCT_ID),
    CONSTRAINT FK_MODEL_PRODUCT_MODEL FOREIGN KEY (MODEL_ID) 
        REFERENCES MODEL(ID) ON DELETE CASCADE,
    CONSTRAINT FK_MODEL_PRODUCT_PRODUCT FOREIGN KEY (PRODUCT_ID) 
        REFERENCES PRODUCT(ID) ON DELETE CASCADE
);

-- Relacionamento: SESSION <-> COLLABORATOR
CREATE TABLE SESSION_COLLABORATOR (
    SESSION_ID NUMBER(19) NOT NULL,
    COLLABORATOR_ID NUMBER(19) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_SESSION_COLLABORATOR PRIMARY KEY (SESSION_ID, COLLABORATOR_ID),
    CONSTRAINT FK_SESSION_COLLABORATOR_SESSION FOREIGN KEY (SESSION_ID) 
        REFERENCES SESSION(ID) ON DELETE CASCADE,
    CONSTRAINT FK_SESSION_COLLABORATOR_COLLABORATOR FOREIGN KEY (COLLABORATOR_ID) 
        REFERENCES COLLABORATOR(ID) ON DELETE CASCADE
);

-- Relacionamento: WAREHOUSE <-> LABORATORY
CREATE TABLE WAREHOUSE_LABORATORY (
    WAREHOUSE_ID NUMBER(19) NOT NULL,
    LABORATORY_ID NUMBER(19) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_WAREHOUSE_LABORATORY PRIMARY KEY (WAREHOUSE_ID, LABORATORY_ID),
    CONSTRAINT FK_WAREHOUSE_LABORATORY_WAREHOUSE FOREIGN KEY (WAREHOUSE_ID) 
        REFERENCES WAREHOUSE(ID) ON DELETE CASCADE,
    CONSTRAINT FK_WAREHOUSE_LABORATORY_LABORATORY FOREIGN KEY (LABORATORY_ID) 
        REFERENCES LABORATORY(ID) ON DELETE CASCADE
);

-- ============================================================================
-- TRIGGERS PARA AUTO INCREMENTO
-- ============================================================================

-- Trigger: SUPPLIER
CREATE OR REPLACE TRIGGER TRG_SUPPLIER_ID
BEFORE INSERT ON SUPPLIER
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT SEQ_SUPPLIER.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
    :NEW.CREATED_AT := CURRENT_TIMESTAMP;
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
END;
/

-- Trigger: BATCH
CREATE OR REPLACE TRIGGER TRG_BATCH_ID
BEFORE INSERT ON BATCH
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT SEQ_BATCH.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
    :NEW.CREATED_AT := CURRENT_TIMESTAMP;
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
END;
/

-- Trigger: MANUFACTURER
CREATE OR REPLACE TRIGGER TRG_MANUFACTURER_ID
BEFORE INSERT ON MANUFACTURER
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT SEQ_MANUFACTURER.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
    :NEW.CREATED_AT := CURRENT_TIMESTAMP;
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
END;
/

-- Trigger: MODEL
CREATE OR REPLACE TRIGGER TRG_MODEL_ID
BEFORE INSERT ON MODEL
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT SEQ_MODEL.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
    :NEW.CREATED_AT := CURRENT_TIMESTAMP;
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
END;
/

-- Trigger: LABORATORY
CREATE OR REPLACE TRIGGER TRG_LABORATORY_ID
BEFORE INSERT ON LABORATORY
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT SEQ_LABORATORY.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
    :NEW.CREATED_AT := CURRENT_TIMESTAMP;
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
END;
/

-- Trigger: WAREHOUSE
CREATE OR REPLACE TRIGGER TRG_WAREHOUSE_ID
BEFORE INSERT ON WAREHOUSE
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT SEQ_WAREHOUSE.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
    :NEW.CREATED_AT := CURRENT_TIMESTAMP;
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
END;
/

-- Trigger: ITEM
CREATE OR REPLACE TRIGGER TRG_ITEM_ID
BEFORE INSERT ON ITEM
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT SEQ_ITEM.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
    :NEW.CREATED_AT := CURRENT_TIMESTAMP;
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
END;
/

-- Trigger: COLLABORATOR
CREATE OR REPLACE TRIGGER TRG_COLLABORATOR_ID
BEFORE INSERT ON COLLABORATOR
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT SEQ_COLLABORATOR.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
    :NEW.CREATED_AT := CURRENT_TIMESTAMP;
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
END;
/

-- Trigger: SESSION
CREATE OR REPLACE TRIGGER TRG_SESSION_ID
BEFORE INSERT ON SESSION
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT SEQ_SESSION.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
    :NEW.CREATED_AT := CURRENT_TIMESTAMP;
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
END;
/

-- Trigger: EVENT
CREATE OR REPLACE TRIGGER TRG_EVENT_ID
BEFORE INSERT ON EVENT
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT SEQ_EVENT.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
    :NEW.CREATED_AT := CURRENT_TIMESTAMP;
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
END;
/

-- Trigger: PRODUCT
CREATE OR REPLACE TRIGGER TRG_PRODUCT_ID
BEFORE INSERT ON PRODUCT
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT SEQ_PRODUCT.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
    :NEW.CREATED_AT := CURRENT_TIMESTAMP;
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
END;
/

-- Triggers para UPDATED_AT
CREATE OR REPLACE TRIGGER TRG_SUPPLIER_UPDATE
BEFORE UPDATE ON SUPPLIER
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_BATCH_UPDATE
BEFORE UPDATE ON BATCH
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_MANUFACTURER_UPDATE
BEFORE UPDATE ON MANUFACTURER
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_MODEL_UPDATE
BEFORE UPDATE ON MODEL
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_LABORATORY_UPDATE
BEFORE UPDATE ON LABORATORY
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_WAREHOUSE_UPDATE
BEFORE UPDATE ON WAREHOUSE
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_ITEM_UPDATE
BEFORE UPDATE ON ITEM
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_COLLABORATOR_UPDATE
BEFORE UPDATE ON COLLABORATOR
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_SESSION_UPDATE
BEFORE UPDATE ON SESSION
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_EVENT_UPDATE
BEFORE UPDATE ON EVENT
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_PRODUCT_UPDATE
BEFORE UPDATE ON PRODUCT
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
END;
/

-- ============================================================================
-- ÍNDICES PARA PERFORMANCE
-- ============================================================================

-- Índices para Foreign Keys
CREATE INDEX IDX_BATCH_SUPPLIER ON BATCH(SUPPLIER_ID_SUPPLIER);
CREATE INDEX IDX_MODEL_MANUFACTURER ON MODEL(MANUFACTURER_ID_MANUFACTURER);
CREATE INDEX IDX_WAREHOUSE_LABORATORY ON WAREHOUSE(LABORATORY_ID_LABORATORY);
CREATE INDEX IDX_PRODUCT_WAREHOUSE ON PRODUCT(WAREHOUSE_ID);
CREATE INDEX IDX_ITEM_MODEL ON ITEM(MODEL_ID_MODEL);
CREATE INDEX IDX_ITEM_BATCH ON ITEM(BATCH_ID_BATCH);
CREATE INDEX IDX_SESSION_WAREHOUSE ON SESSION(WAREHOUSE_ID_WAREHOUSE);
CREATE INDEX IDX_SESSION_COLLABORATOR ON SESSION(COLLABORATOR_ID_COLLABORATOR);
CREATE INDEX IDX_EVENT_ITEM ON EVENT(ITEM_ID_ITEM);

-- Índices para campos comuns em consultas
CREATE INDEX IDX_PRODUCT_STATUS ON PRODUCT(STATUS);
CREATE INDEX IDX_PRODUCT_VALIDITY ON PRODUCT(VALIDITY_DATE);
CREATE INDEX IDX_SESSION_DATES ON SESSION(START, "END");

-- ============================================================================
-- DADOS DE EXEMPLO (OPCIONAL - comentado por padrão)
-- ============================================================================

/*
-- Inserir Laboratórios
INSERT INTO LABORATORY (NM_LABORATORY) VALUES ('Laboratório Central');
INSERT INTO LABORATORY (NM_LABORATORY) VALUES ('Laboratório Norte');
INSERT INTO LABORATORY (NM_LABORATORY) VALUES ('Laboratório Sul');

-- Inserir Fabricantes
INSERT INTO MANUFACTURER (NM_MANUFACTURER) VALUES ('Samsung Electronics');
INSERT INTO MANUFACTURER (NM_MANUFACTURER) VALUES ('Apple Inc.');
INSERT INTO MANUFACTURER (NM_MANUFACTURER) VALUES ('Dell Technologies');

-- Inserir Fornecedores
INSERT INTO SUPPLIER (NM_SUPPLIER, CPF) VALUES ('Tech Supply LTDA', '12345678901');
INSERT INTO SUPPLIER (NM_SUPPLIER, CPF) VALUES ('Digital Imports S.A.', '98765432109');

-- Inserir Colaboradores
INSERT INTO COLLABORATOR (NM_COLLABORATOR, COD_COMPANY, CPF) VALUES ('João da Silva', 'EMP001', '11122233344');
INSERT INTO COLLABORATOR (NM_COLLABORATOR, COD_COMPANY, CPF) VALUES ('Maria Santos', 'EMP002', '55566677788');

COMMIT;
*/

-- ============================================================================
-- FIM DO SCRIPT
-- ============================================================================
COMMIT;

SELECT 'Database schema created successfully!' AS MESSAGE FROM DUAL;
