server:
  port: 8080

spring:
  datasource:
    url: ${ORACLE_URL:jdbc:oracle:thin:@oracle.fiap.com.br:1521:orcl}
    username: ${ORACLE_USER:rm558982}
    password: ${ORACLE_PASSWORD:050505}
    driver-class-name: oracle.jdbc.OracleDriver